'''
Created on Aug 15, 2016

@author: Jacob
'''
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1084, 813)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MatchInputsGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MatchInputsGroupBox.setFont(font)
        self.MatchInputsGroupBox.setObjectName(_fromUtf8("MatchInputsGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.MatchInputsGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.MatchNumberLabel = QtGui.QLabel(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MatchNumberLabel.setFont(font)
        self.MatchNumberLabel.setObjectName(_fromUtf8("MatchNumberLabel"))
        self.horizontalLayout_3.addWidget(self.MatchNumberLabel)
        self.matchNumberSpinBox = QtGui.QSpinBox(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matchNumberSpinBox.setFont(font)
        self.matchNumberSpinBox.setObjectName(_fromUtf8("matchNumberSpinBox"))
        self.horizontalLayout_3.addWidget(self.matchNumberSpinBox)
        self.CreateMatchPushBtn = QtGui.QPushButton(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CreateMatchPushBtn.setFont(font)
        self.CreateMatchPushBtn.setObjectName(_fromUtf8("CreateMatchPushBtn"))
        self.horizontalLayout_3.addWidget(self.CreateMatchPushBtn)
        self.ReloadDataPushBtn = QtGui.QPushButton(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ReloadDataPushBtn.setFont(font)
        self.ReloadDataPushBtn.setObjectName(_fromUtf8("ReloadDataPushBtn"))
        self.horizontalLayout_3.addWidget(self.ReloadDataPushBtn)
        self.progressBar = QtGui.QProgressBar(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.ErrorTextLine = QtGui.QLineEdit(self.MatchInputsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ErrorTextLine.setFont(font)
        self.ErrorTextLine.setObjectName(_fromUtf8("ErrorTextLine"))
        self.horizontalLayout_3.addWidget(self.ErrorTextLine)
        self.gridLayout.addWidget(self.MatchInputsGroupBox, 0, 0, 1, 1)
        self.DataVisualizationGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DataVisualizationGroupBox.setFont(font)
        self.DataVisualizationGroupBox.setObjectName(_fromUtf8("DataVisualizationGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.DataVisualizationGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.graphicsViewLeft = QtGui.QGraphicsView(self.DataVisualizationGroupBox)
        self.graphicsViewLeft.setObjectName(_fromUtf8("graphicsViewLeft"))
        self.horizontalLayout.addWidget(self.graphicsViewLeft)
        self.graphicsViewRight = QtGui.QGraphicsView(self.DataVisualizationGroupBox)
        self.graphicsViewRight.setObjectName(_fromUtf8("graphicsViewRight"))
        self.horizontalLayout.addWidget(self.graphicsViewRight)
        self.gridLayout.addWidget(self.DataVisualizationGroupBox, 1, 0, 1, 1)
        self.ContainerBottom = QtGui.QWidget(self.centralwidget)
        self.ContainerBottom.setObjectName(_fromUtf8("ContainerBottom"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ContainerBottom)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabsLeft = QtGui.QTabWidget(self.ContainerBottom)
        self.tabsLeft.setObjectName(_fromUtf8("tabsLeft"))
        self.dataTabLeft = QtGui.QWidget()
        self.dataTabLeft.setObjectName(_fromUtf8("dataTabLeft"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dataTabLeft)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.DataSelectionGroupBoxLeft = QtGui.QGroupBox(self.dataTabLeft)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DataSelectionGroupBoxLeft.setFont(font)
        self.DataSelectionGroupBoxLeft.setObjectName(_fromUtf8("DataSelectionGroupBoxLeft"))
        self.gridLayout_4 = QtGui.QGridLayout(self.DataSelectionGroupBoxLeft)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.playerComboBoxLeft = QtGui.QComboBox(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.playerComboBoxLeft.setFont(font)
        self.playerComboBoxLeft.setObjectName(_fromUtf8("playerComboBoxLeft"))
        self.playerComboBoxLeft.addItem(_fromUtf8(""))
        self.playerComboBoxLeft.setItemText(0, _fromUtf8(""))
        self.playerComboBoxLeft.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.playerComboBoxLeft, 7, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.halfLabelLeft = QtGui.QLabel(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.halfLabelLeft.setFont(font)
        self.halfLabelLeft.setObjectName(_fromUtf8("halfLabelLeft"))
        self.gridLayout_4.addWidget(self.halfLabelLeft, 2, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.teamComboBoxLeft = QtGui.QComboBox(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teamComboBoxLeft.setFont(font)
        self.teamComboBoxLeft.setObjectName(_fromUtf8("teamComboBoxLeft"))
        self.teamComboBoxLeft.addItem(_fromUtf8(""))
        self.teamComboBoxLeft.setItemText(0, _fromUtf8(""))
        self.teamComboBoxLeft.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.teamComboBoxLeft, 5, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.matchLabelLeft = QtGui.QLabel(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matchLabelLeft.setFont(font)
        self.matchLabelLeft.setObjectName(_fromUtf8("matchLabelLeft"))
        self.gridLayout_4.addWidget(self.matchLabelLeft, 0, 0, 1, 1)
        self.matchComboBoxLeft = QtGui.QComboBox(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matchComboBoxLeft.setFont(font)
        self.matchComboBoxLeft.setObjectName(_fromUtf8("matchComboBoxLeft"))
        self.matchComboBoxLeft.addItem(_fromUtf8(""))
        self.matchComboBoxLeft.setItemText(0, _fromUtf8(""))
        self.matchComboBoxLeft.addItem(_fromUtf8(""))
        self.matchComboBoxLeft.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.matchComboBoxLeft, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.findBtnLeft = QtGui.QPushButton(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.findBtnLeft.setFont(font)
        self.findBtnLeft.setObjectName(_fromUtf8("findBtnLeft"))
        self.gridLayout_4.addWidget(self.findBtnLeft, 8, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.teamLabelLeft = QtGui.QLabel(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teamLabelLeft.setFont(font)
        self.teamLabelLeft.setObjectName(_fromUtf8("teamLabelLeft"))
        self.gridLayout_4.addWidget(self.teamLabelLeft, 4, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.playerLabelLeft = QtGui.QLabel(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.playerLabelLeft.setFont(font)
        self.playerLabelLeft.setObjectName(_fromUtf8("playerLabelLeft"))
        self.gridLayout_4.addWidget(self.playerLabelLeft, 6, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.halfComboBoxLeft = QtGui.QComboBox(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.halfComboBoxLeft.setFont(font)
        self.halfComboBoxLeft.setObjectName(_fromUtf8("halfComboBoxLeft"))
        self.halfComboBoxLeft.addItem(_fromUtf8(""))
        self.halfComboBoxLeft.setItemText(0, _fromUtf8(""))
        self.halfComboBoxLeft.addItem(_fromUtf8(""))
        self.halfComboBoxLeft.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.halfComboBoxLeft, 3, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.clearBtnLeft = QtGui.QPushButton(self.DataSelectionGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clearBtnLeft.setFont(font)
        self.clearBtnLeft.setObjectName(_fromUtf8("clearBtnLeft"))
        self.gridLayout_4.addWidget(self.clearBtnLeft, 9, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_3.addWidget(self.DataSelectionGroupBoxLeft, 0, 0, 1, 1)
        self.tabsLeft.addTab(self.dataTabLeft, _fromUtf8(""))
        self.teamTabLeft = QtGui.QWidget()
        self.teamTabLeft.setObjectName(_fromUtf8("teamTabLeft"))
        self.gridLayout_6 = QtGui.QGridLayout(self.teamTabLeft)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.teamGroupBoxLeft = QtGui.QGroupBox(self.teamTabLeft)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teamGroupBoxLeft.setFont(font)
        self.teamGroupBoxLeft.setObjectName(_fromUtf8("teamGroupBoxLeft"))
        self.gridLayout_5 = QtGui.QGridLayout(self.teamGroupBoxLeft)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.teamNameLeft = QtGui.QLabel(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.teamNameLeft.setFont(font)
        self.teamNameLeft.setObjectName(_fromUtf8("teamNameLeft"))
        self.gridLayout_5.addWidget(self.teamNameLeft, 0, 0, 1, 1)
        self.lineLeft = QtGui.QFrame(self.teamGroupBoxLeft)
        self.lineLeft.setFrameShape(QtGui.QFrame.HLine)
        self.lineLeft.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineLeft.setObjectName(_fromUtf8("lineLeft"))
        self.gridLayout_5.addWidget(self.lineLeft, 1, 0, 1, 1)
        self.winsLeft = QtGui.QLabel(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.winsLeft.setFont(font)
        self.winsLeft.setObjectName(_fromUtf8("winsLeft"))
        self.gridLayout_5.addWidget(self.winsLeft, 2, 0, 1, 1)
        self.lossesLeft = QtGui.QLabel(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lossesLeft.setFont(font)
        self.lossesLeft.setObjectName(_fromUtf8("lossesLeft"))
        self.gridLayout_5.addWidget(self.lossesLeft, 3, 0, 1, 1)
        self.wLRatioLeft = QtGui.QLabel(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wLRatioLeft.setFont(font)
        self.wLRatioLeft.setObjectName(_fromUtf8("wLRatioLeft"))
        self.gridLayout_5.addWidget(self.wLRatioLeft, 4, 0, 1, 1)
        self.otherLeft = QtGui.QLabel(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.otherLeft.setFont(font)
        self.otherLeft.setObjectName(_fromUtf8("otherLeft"))
        self.gridLayout_5.addWidget(self.otherLeft, 5, 0, 1, 1)
        self.dataVizTeamLeft_1 = QtGui.QPushButton(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamLeft_1.setFont(font)
        self.dataVizTeamLeft_1.setObjectName(_fromUtf8("dataVizTeamLeft_1"))
        self.gridLayout_5.addWidget(self.dataVizTeamLeft_1, 6, 0, 1, 1)
        self.dataVizTeamLeft_2 = QtGui.QPushButton(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamLeft_2.setFont(font)
        self.dataVizTeamLeft_2.setObjectName(_fromUtf8("dataVizTeamLeft_2"))
        self.gridLayout_5.addWidget(self.dataVizTeamLeft_2, 7, 0, 1, 1)
        self.dataVizTeamLeft_3 = QtGui.QPushButton(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamLeft_3.setFont(font)
        self.dataVizTeamLeft_3.setObjectName(_fromUtf8("dataVizTeamLeft_3"))
        self.gridLayout_5.addWidget(self.dataVizTeamLeft_3, 8, 0, 1, 1)
        self.dataVizTeamLeft_4 = QtGui.QPushButton(self.teamGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamLeft_4.setFont(font)
        self.dataVizTeamLeft_4.setObjectName(_fromUtf8("dataVizTeamLeft_4"))
        self.gridLayout_5.addWidget(self.dataVizTeamLeft_4, 9, 0, 1, 1)
        self.gridLayout_6.addWidget(self.teamGroupBoxLeft, 0, 0, 1, 1)
        self.tabsLeft.addTab(self.teamTabLeft, _fromUtf8(""))
        self.playerTabLeft = QtGui.QWidget()
        self.playerTabLeft.setObjectName(_fromUtf8("playerTabLeft"))
        self.gridLayout_7 = QtGui.QGridLayout(self.playerTabLeft)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.PlayerGroupBoxLeft = QtGui.QGroupBox(self.playerTabLeft)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PlayerGroupBoxLeft.setFont(font)
        self.PlayerGroupBoxLeft.setObjectName(_fromUtf8("PlayerGroupBoxLeft"))
        self.verticalLayout = QtGui.QVBoxLayout(self.PlayerGroupBoxLeft)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.playerNameLabelLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.playerNameLabelLeft.setFont(font)
        self.playerNameLabelLeft.setObjectName(_fromUtf8("playerNameLabelLeft"))
        self.verticalLayout.addWidget(self.playerNameLabelLeft)
        self.lineLeft_2 = QtGui.QFrame(self.PlayerGroupBoxLeft)
        self.lineLeft_2.setFrameShape(QtGui.QFrame.HLine)
        self.lineLeft_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineLeft_2.setObjectName(_fromUtf8("lineLeft_2"))
        self.verticalLayout.addWidget(self.lineLeft_2)
        self.killsLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.killsLeft.setFont(font)
        self.killsLeft.setObjectName(_fromUtf8("killsLeft"))
        self.verticalLayout.addWidget(self.killsLeft, QtCore.Qt.AlignBottom)
        self.deathsLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.deathsLeft.setFont(font)
        self.deathsLeft.setObjectName(_fromUtf8("deathsLeft"))
        self.verticalLayout.addWidget(self.deathsLeft, QtCore.Qt.AlignBottom)
        self.assistsLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.assistsLeft.setFont(font)
        self.assistsLeft.setObjectName(_fromUtf8("assistsLeft"))
        self.verticalLayout.addWidget(self.assistsLeft, QtCore.Qt.AlignBottom)
        self.kDRatioLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.kDRatioLeft.setFont(font)
        self.kDRatioLeft.setObjectName(_fromUtf8("kDRatioLeft"))
        self.verticalLayout.addWidget(self.kDRatioLeft, QtCore.Qt.AlignBottom)
        self.isArcherLeft = QtGui.QLabel(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.isArcherLeft.setFont(font)
        self.isArcherLeft.setObjectName(_fromUtf8("isArcherLeft"))
        self.verticalLayout.addWidget(self.isArcherLeft, QtCore.Qt.AlignBottom)
        self.dataVizPlayerLeft_1 = QtGui.QPushButton(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerLeft_1.setFont(font)
        self.dataVizPlayerLeft_1.setObjectName(_fromUtf8("dataVizPlayerLeft_1"))
        self.verticalLayout.addWidget(self.dataVizPlayerLeft_1)
        self.dataVizPlayerLeft_2 = QtGui.QPushButton(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerLeft_2.setFont(font)
        self.dataVizPlayerLeft_2.setObjectName(_fromUtf8("dataVizPlayerLeft_2"))
        self.verticalLayout.addWidget(self.dataVizPlayerLeft_2)
        self.dataVizPlayerLeft_3 = QtGui.QPushButton(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerLeft_3.setFont(font)
        self.dataVizPlayerLeft_3.setObjectName(_fromUtf8("dataVizPlayerLeft_3"))
        self.verticalLayout.addWidget(self.dataVizPlayerLeft_3)
        self.dataVizPlayerLeft_4 = QtGui.QPushButton(self.PlayerGroupBoxLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerLeft_4.setFont(font)
        self.dataVizPlayerLeft_4.setObjectName(_fromUtf8("dataVizPlayerLeft_4"))
        self.verticalLayout.addWidget(self.dataVizPlayerLeft_4)
        self.gridLayout_7.addWidget(self.PlayerGroupBoxLeft, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.tabsLeft.addTab(self.playerTabLeft, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabsLeft)
        self.tabsRight = QtGui.QTabWidget(self.ContainerBottom)
        self.tabsRight.setObjectName(_fromUtf8("tabsRight"))
        self.dataTabRight = QtGui.QWidget()
        self.dataTabRight.setObjectName(_fromUtf8("dataTabRight"))
        self.gridLayout_9 = QtGui.QGridLayout(self.dataTabRight)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.DataSelectionGroupBoxRight = QtGui.QGroupBox(self.dataTabRight)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DataSelectionGroupBoxRight.setFont(font)
        self.DataSelectionGroupBoxRight.setObjectName(_fromUtf8("DataSelectionGroupBoxRight"))
        self.gridLayout_8 = QtGui.QGridLayout(self.DataSelectionGroupBoxRight)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.playerLabelRight = QtGui.QLabel(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.playerLabelRight.setFont(font)
        self.playerLabelRight.setObjectName(_fromUtf8("playerLabelRight"))
        self.gridLayout_8.addWidget(self.playerLabelRight, 7, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.halfComboBoxRight = QtGui.QComboBox(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.halfComboBoxRight.setFont(font)
        self.halfComboBoxRight.setObjectName(_fromUtf8("halfComboBoxRight"))
        self.halfComboBoxRight.addItem(_fromUtf8(""))
        self.halfComboBoxRight.setItemText(0, _fromUtf8(""))
        self.halfComboBoxRight.addItem(_fromUtf8(""))
        self.halfComboBoxRight.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.halfComboBoxRight, 3, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.matchLabelRight = QtGui.QLabel(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matchLabelRight.setFont(font)
        self.matchLabelRight.setObjectName(_fromUtf8("matchLabelRight"))
        self.gridLayout_8.addWidget(self.matchLabelRight, 0, 0, 1, 1)
        self.matchComboBoxRight = QtGui.QComboBox(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matchComboBoxRight.setFont(font)
        self.matchComboBoxRight.setObjectName(_fromUtf8("matchComboBoxRight"))
        self.matchComboBoxRight.addItem(_fromUtf8(""))
        self.matchComboBoxRight.setItemText(0, _fromUtf8(""))
        self.matchComboBoxRight.addItem(_fromUtf8(""))
        self.matchComboBoxRight.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.matchComboBoxRight, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.clearBtnRight = QtGui.QPushButton(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clearBtnRight.setFont(font)
        self.clearBtnRight.setObjectName(_fromUtf8("clearBtnRight"))
        self.gridLayout_8.addWidget(self.clearBtnRight, 10, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.findBtnRight = QtGui.QPushButton(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.findBtnRight.setFont(font)
        self.findBtnRight.setObjectName(_fromUtf8("findBtnRight"))
        self.gridLayout_8.addWidget(self.findBtnRight, 9, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.halfLabelRight = QtGui.QLabel(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.halfLabelRight.setFont(font)
        self.halfLabelRight.setObjectName(_fromUtf8("halfLabelRight"))
        self.gridLayout_8.addWidget(self.halfLabelRight, 2, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.playerComboBoxRight = QtGui.QComboBox(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.playerComboBoxRight.setFont(font)
        self.playerComboBoxRight.setObjectName(_fromUtf8("playerComboBoxRight"))
        self.playerComboBoxRight.addItem(_fromUtf8(""))
        self.playerComboBoxRight.setItemText(0, _fromUtf8(""))
        self.playerComboBoxRight.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.playerComboBoxRight, 8, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.teamLabelRight = QtGui.QLabel(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teamLabelRight.setFont(font)
        self.teamLabelRight.setObjectName(_fromUtf8("teamLabelRight"))
        self.gridLayout_8.addWidget(self.teamLabelRight, 4, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.teamComboBoxRight = QtGui.QComboBox(self.DataSelectionGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teamComboBoxRight.setFont(font)
        self.teamComboBoxRight.setObjectName(_fromUtf8("teamComboBoxRight"))
        self.teamComboBoxRight.addItem(_fromUtf8(""))
        self.teamComboBoxRight.setItemText(0, _fromUtf8(""))
        self.teamComboBoxRight.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.teamComboBoxRight, 5, 0, 1, 1)
        self.gridLayout_9.addWidget(self.DataSelectionGroupBoxRight, 0, 0, 1, 1)
        self.tabsRight.addTab(self.dataTabRight, _fromUtf8(""))
        self.teamTabRight = QtGui.QWidget()
        self.teamTabRight.setObjectName(_fromUtf8("teamTabRight"))
        self.gridLayout_11 = QtGui.QGridLayout(self.teamTabRight)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.teamGroupBoxRight = QtGui.QGroupBox(self.teamTabRight)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teamGroupBoxRight.setFont(font)
        self.teamGroupBoxRight.setObjectName(_fromUtf8("teamGroupBoxRight"))
        self.gridLayout_10 = QtGui.QGridLayout(self.teamGroupBoxRight)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.teamNameRight = QtGui.QLabel(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.teamNameRight.setFont(font)
        self.teamNameRight.setObjectName(_fromUtf8("teamNameRight"))
        self.gridLayout_10.addWidget(self.teamNameRight, 0, 0, 1, 1)
        self.lineRight = QtGui.QFrame(self.teamGroupBoxRight)
        self.lineRight.setFrameShape(QtGui.QFrame.HLine)
        self.lineRight.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRight.setObjectName(_fromUtf8("lineRight"))
        self.gridLayout_10.addWidget(self.lineRight, 1, 0, 1, 1)
        self.winsRight = QtGui.QLabel(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.winsRight.setFont(font)
        self.winsRight.setObjectName(_fromUtf8("winsRight"))
        self.gridLayout_10.addWidget(self.winsRight, 2, 0, 1, 1)
        self.lossesRight = QtGui.QLabel(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lossesRight.setFont(font)
        self.lossesRight.setObjectName(_fromUtf8("lossesRight"))
        self.gridLayout_10.addWidget(self.lossesRight, 3, 0, 1, 1)
        self.wLRatioRight = QtGui.QLabel(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wLRatioRight.setFont(font)
        self.wLRatioRight.setObjectName(_fromUtf8("wLRatioRight"))
        self.gridLayout_10.addWidget(self.wLRatioRight, 4, 0, 1, 1)
        self.otherRight = QtGui.QLabel(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.otherRight.setFont(font)
        self.otherRight.setObjectName(_fromUtf8("otherRight"))
        self.gridLayout_10.addWidget(self.otherRight, 5, 0, 1, 1)
        self.dataVizTeamRight_1 = QtGui.QPushButton(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamRight_1.setFont(font)
        self.dataVizTeamRight_1.setObjectName(_fromUtf8("dataVizTeamRight_1"))
        self.gridLayout_10.addWidget(self.dataVizTeamRight_1, 6, 0, 1, 1)
        self.dataVizTeamRight_2 = QtGui.QPushButton(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamRight_2.setFont(font)
        self.dataVizTeamRight_2.setObjectName(_fromUtf8("dataVizTeamRight_2"))
        self.gridLayout_10.addWidget(self.dataVizTeamRight_2, 7, 0, 1, 1)
        self.dataVizTeamRight_3 = QtGui.QPushButton(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamRight_3.setFont(font)
        self.dataVizTeamRight_3.setObjectName(_fromUtf8("dataVizTeamRight_3"))
        self.gridLayout_10.addWidget(self.dataVizTeamRight_3, 8, 0, 1, 1)
        self.dataVizTeamRight_4 = QtGui.QPushButton(self.teamGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizTeamRight_4.setFont(font)
        self.dataVizTeamRight_4.setObjectName(_fromUtf8("dataVizTeamRight_4"))
        self.gridLayout_10.addWidget(self.dataVizTeamRight_4, 9, 0, 1, 1)
        self.gridLayout_11.addWidget(self.teamGroupBoxRight, 0, 0, 1, 1)
        self.tabsRight.addTab(self.teamTabRight, _fromUtf8(""))
        self.playerTabRight = QtGui.QWidget()
        self.playerTabRight.setObjectName(_fromUtf8("playerTabRight"))
        self.gridLayout_13 = QtGui.QGridLayout(self.playerTabRight)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.PlayerGroupBoxRight = QtGui.QGroupBox(self.playerTabRight)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PlayerGroupBoxRight.setFont(font)
        self.PlayerGroupBoxRight.setObjectName(_fromUtf8("PlayerGroupBoxRight"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.PlayerGroupBoxRight)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.playerNameLabelRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.playerNameLabelRight.setFont(font)
        self.playerNameLabelRight.setObjectName(_fromUtf8("playerNameLabelRight"))
        self.verticalLayout_2.addWidget(self.playerNameLabelRight)
        self.lineRight_2 = QtGui.QFrame(self.PlayerGroupBoxRight)
        self.lineRight_2.setFrameShape(QtGui.QFrame.HLine)
        self.lineRight_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRight_2.setObjectName(_fromUtf8("lineRight_2"))
        self.verticalLayout_2.addWidget(self.lineRight_2)
        self.killsRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.killsRight.setFont(font)
        self.killsRight.setObjectName(_fromUtf8("killsRight"))
        self.verticalLayout_2.addWidget(self.killsRight, QtCore.Qt.AlignBottom)
        self.deathsRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.deathsRight.setFont(font)
        self.deathsRight.setObjectName(_fromUtf8("deathsRight"))
        self.verticalLayout_2.addWidget(self.deathsRight, QtCore.Qt.AlignBottom)
        self.assistsRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.assistsRight.setFont(font)
        self.assistsRight.setObjectName(_fromUtf8("assistsRight"))
        self.verticalLayout_2.addWidget(self.assistsRight, QtCore.Qt.AlignBottom)
        self.kDRatioRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.kDRatioRight.setFont(font)
        self.kDRatioRight.setObjectName(_fromUtf8("kDRatioRight"))
        self.verticalLayout_2.addWidget(self.kDRatioRight, QtCore.Qt.AlignBottom)
        self.isArcherRight = QtGui.QLabel(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.isArcherRight.setFont(font)
        self.isArcherRight.setObjectName(_fromUtf8("isArcherRight"))
        self.verticalLayout_2.addWidget(self.isArcherRight, QtCore.Qt.AlignBottom)
        self.dataVizPlayerRight_1 = QtGui.QPushButton(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerRight_1.setFont(font)
        self.dataVizPlayerRight_1.setObjectName(_fromUtf8("dataVizPlayerRight_1"))
        self.verticalLayout_2.addWidget(self.dataVizPlayerRight_1)
        self.dataVizPlayerRight_2 = QtGui.QPushButton(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerRight_2.setFont(font)
        self.dataVizPlayerRight_2.setObjectName(_fromUtf8("dataVizPlayerRight_2"))
        self.verticalLayout_2.addWidget(self.dataVizPlayerRight_2)
        self.dataVizPlayerRight_3 = QtGui.QPushButton(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerRight_3.setFont(font)
        self.dataVizPlayerRight_3.setObjectName(_fromUtf8("dataVizPlayerRight_3"))
        self.verticalLayout_2.addWidget(self.dataVizPlayerRight_3)
        self.dataVizPlayerRight_4 = QtGui.QPushButton(self.PlayerGroupBoxRight)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataVizPlayerRight_4.setFont(font)
        self.dataVizPlayerRight_4.setObjectName(_fromUtf8("dataVizPlayerRight_4"))
        self.verticalLayout_2.addWidget(self.dataVizPlayerRight_4)
        self.gridLayout_13.addWidget(self.PlayerGroupBoxRight, 0, 0, 1, 1)
        self.tabsRight.addTab(self.playerTabRight, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabsRight)
        self.gridLayout.addWidget(self.ContainerBottom, 2, 0, 1, 1, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabsLeft.setCurrentIndex(2)
        self.tabsRight.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Harambe\'s Chivalry Data Cruncher", None))
        self.MatchInputsGroupBox.setTitle(_translate("MainWindow", "Match Inputs", None))
        self.MatchNumberLabel.setText(_translate("MainWindow", "Match Number", None))
        self.CreateMatchPushBtn.setText(_translate("MainWindow", "Create Match", None))
        self.ReloadDataPushBtn.setText(_translate("MainWindow", "Reload Data", None))
        self.DataVisualizationGroupBox.setTitle(_translate("MainWindow", "Data Visualization", None))
        self.DataSelectionGroupBoxLeft.setTitle(_translate("MainWindow", "Data Selection", None))
        self.playerComboBoxLeft.setItemText(1, _translate("MainWindow", "Crimson King", None))
        self.halfLabelLeft.setText(_translate("MainWindow", "Half", None))
        self.teamComboBoxLeft.setItemText(1, _translate("MainWindow", "Harambe", None))
        self.matchLabelLeft.setText(_translate("MainWindow", "Match", None))
        self.matchComboBoxLeft.setItemText(1, _translate("MainWindow", "Number One", None))
        self.matchComboBoxLeft.setItemText(2, _translate("MainWindow", "Number Two", None))
        self.findBtnLeft.setText(_translate("MainWindow", "Find", None))
        self.teamLabelLeft.setText(_translate("MainWindow", "Team", None))
        self.playerLabelLeft.setText(_translate("MainWindow", "Player", None))
        self.halfComboBoxLeft.setItemText(1, _translate("MainWindow", "Number One", None))
        self.halfComboBoxLeft.setItemText(2, _translate("MainWindow", "Number Two", None))
        self.clearBtnLeft.setText(_translate("MainWindow", "Clear", None))
        self.tabsLeft.setTabText(self.tabsLeft.indexOf(self.dataTabLeft), _translate("MainWindow", "Data Selection", None))
        self.teamGroupBoxLeft.setTitle(_translate("MainWindow", "Team", None))
        self.teamNameLeft.setText(_translate("MainWindow", "Accolade", None))
        self.winsLeft.setText(_translate("MainWindow", "Wins: ", None))
        self.lossesLeft.setText(_translate("MainWindow", "Losses:", None))
        self.wLRatioLeft.setText(_translate("MainWindow", "Win Loss Ratio :", None))
        self.otherLeft.setText(_translate("MainWindow", "Other :", None))
        self.dataVizTeamLeft_1.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamLeft_2.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamLeft_3.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamLeft_4.setText(_translate("MainWindow", "Data Viz ", None))
        self.tabsLeft.setTabText(self.tabsLeft.indexOf(self.teamTabLeft), _translate("MainWindow", "Team", None))
        self.PlayerGroupBoxLeft.setTitle(_translate("MainWindow", "Player", None))
        self.playerNameLabelLeft.setText(_translate("MainWindow", "Crimson King", None))
        self.killsLeft.setText(_translate("MainWindow", "Kills:", None))
        self.deathsLeft.setText(_translate("MainWindow", "Deaths:", None))
        self.assistsLeft.setText(_translate("MainWindow", "Assists:", None))
        self.kDRatioLeft.setText(_translate("MainWindow", "K/D Ratio:", None))
        self.isArcherLeft.setText(_translate("MainWindow", "Is Archer:", None))
        self.dataVizPlayerLeft_1.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerLeft_2.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerLeft_3.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerLeft_4.setText(_translate("MainWindow", "Data Viz ", None))
        self.tabsLeft.setTabText(self.tabsLeft.indexOf(self.playerTabLeft), _translate("MainWindow", "Player", None))
        self.DataSelectionGroupBoxRight.setTitle(_translate("MainWindow", "Data Selection", None))
        self.playerLabelRight.setText(_translate("MainWindow", "Player", None))
        self.halfComboBoxRight.setItemText(1, _translate("MainWindow", "Number One", None))
        self.halfComboBoxRight.setItemText(2, _translate("MainWindow", "Number Two", None))
        self.matchLabelRight.setText(_translate("MainWindow", "Match", None))
        self.matchComboBoxRight.setItemText(1, _translate("MainWindow", "Number One", None))
        self.matchComboBoxRight.setItemText(2, _translate("MainWindow", "Number Two", None))
        self.clearBtnRight.setText(_translate("MainWindow", "Clear", None))
        self.findBtnRight.setText(_translate("MainWindow", "Find", None))
        self.halfLabelRight.setText(_translate("MainWindow", "Half", None))
        self.playerComboBoxRight.setItemText(1, _translate("MainWindow", "Crimson King", None))
        self.teamLabelRight.setText(_translate("MainWindow", "Team", None))
        self.teamComboBoxRight.setItemText(1, _translate("MainWindow", "Harambe", None))
        self.tabsRight.setTabText(self.tabsRight.indexOf(self.dataTabRight), _translate("MainWindow", "Data Selection", None))
        self.teamGroupBoxRight.setTitle(_translate("MainWindow", "Team", None))
        self.teamNameRight.setText(_translate("MainWindow", "Accolade", None))
        self.winsRight.setText(_translate("MainWindow", "Wins: ", None))
        self.lossesRight.setText(_translate("MainWindow", "Losses:", None))
        self.wLRatioRight.setText(_translate("MainWindow", "Win Loss Ratio :", None))
        self.otherRight.setText(_translate("MainWindow", "Other :", None))
        self.dataVizTeamRight_1.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamRight_2.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamRight_3.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizTeamRight_4.setText(_translate("MainWindow", "Data Viz ", None))
        self.tabsRight.setTabText(self.tabsRight.indexOf(self.teamTabRight), _translate("MainWindow", "Team", None))
        self.PlayerGroupBoxRight.setTitle(_translate("MainWindow", "Player", None))
        self.playerNameLabelRight.setText(_translate("MainWindow", "Crimson King", None))
        self.killsRight.setText(_translate("MainWindow", "Kills:", None))
        self.deathsRight.setText(_translate("MainWindow", "Deaths:", None))
        self.assistsRight.setText(_translate("MainWindow", "Assists:", None))
        self.kDRatioRight.setText(_translate("MainWindow", "K/D Ratio:", None))
        self.isArcherRight.setText(_translate("MainWindow", "Is Archer:", None))
        self.dataVizPlayerRight_1.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerRight_2.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerRight_3.setText(_translate("MainWindow", "Data Viz ", None))
        self.dataVizPlayerRight_4.setText(_translate("MainWindow", "Data Viz ", None))
        self.tabsRight.setTabText(self.tabsRight.indexOf(self.playerTabRight), _translate("MainWindow", "Player", None))


def run():
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()

    